package colombia.dian.wcf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2020-02-06T23:56:32.669+07:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://wcf.dian.colombia", name = "IWcfDianCustomerServices")
@XmlSeeAlso({org.datacontract.schemas._2004._07.uploaddocumentresponse.ObjectFactory.class, ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, org.datacontract.schemas._2004._07.dianresponse.ObjectFactory.class, org.datacontract.schemas._2004._07.numberrangeresponselist.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, org.datacontract.schemas._2004._07.numberrangeresponse.ObjectFactory.class, org.datacontract.schemas._2004._07.xmlparamsresponsetrackid.ObjectFactory.class, org.datacontract.schemas._2004._07.eventresponse.ObjectFactory.class, org.datacontract.schemas._2004._07.exchangeemailresponse.ObjectFactory.class})
public interface IWcfDianCustomerServices {

    @WebMethod(operationName = "SendEventUpdateStatus", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendEventUpdateStatus")
    @Action(input = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendEventUpdateStatus", output = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendEventUpdateStatusResponse")
    @RequestWrapper(localName = "SendEventUpdateStatus", targetNamespace = "http://wcf.dian.colombia", className = "colombia.dian.wcf.SendEventUpdateStatus")
    @ResponseWrapper(localName = "SendEventUpdateStatusResponse", targetNamespace = "http://wcf.dian.colombia", className = "colombia.dian.wcf.SendEventUpdateStatusResponse")
    @WebResult(name = "SendEventUpdateStatusResult", targetNamespace = "http://wcf.dian.colombia")
    public org.datacontract.schemas._2004._07.eventresponse.ArrayOfEventResponse sendEventUpdateStatus(
        @WebParam(name = "contentFile", targetNamespace = "http://wcf.dian.colombia")
        byte[] contentFile
    );

    @WebMethod(operationName = "GetNumberingRange", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetNumberingRange")
    @Action(input = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetNumberingRange", output = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetNumberingRangeResponse")
    @RequestWrapper(localName = "GetNumberingRange", targetNamespace = "http://wcf.dian.colombia", className = "colombia.dian.wcf.GetNumberingRange")
    @ResponseWrapper(localName = "GetNumberingRangeResponse", targetNamespace = "http://wcf.dian.colombia", className = "colombia.dian.wcf.GetNumberingRangeResponse")
    @WebResult(name = "GetNumberingRangeResult", targetNamespace = "http://wcf.dian.colombia")
    public org.datacontract.schemas._2004._07.numberrangeresponselist.NumberRangeResponseList getNumberingRange(
        @WebParam(name = "accountCode", targetNamespace = "http://wcf.dian.colombia")
        java.lang.String accountCode,
        @WebParam(name = "accountCodeT", targetNamespace = "http://wcf.dian.colombia")
        java.lang.String accountCodeT,
        @WebParam(name = "softwareCode", targetNamespace = "http://wcf.dian.colombia")
        java.lang.String softwareCode
    );

    @WebMethod(operationName = "SendBillAsync", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendBillAsync")
    @Action(input = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendBillAsync", output = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendBillAsyncResponse")
    @RequestWrapper(localName = "SendBillAsync", targetNamespace = "http://wcf.dian.colombia", className = "colombia.dian.wcf.SendBillAsync")
    @ResponseWrapper(localName = "SendBillAsyncResponse", targetNamespace = "http://wcf.dian.colombia", className = "colombia.dian.wcf.SendBillAsyncResponse")
    @WebResult(name = "SendBillAsyncResult", targetNamespace = "http://wcf.dian.colombia")
    public org.datacontract.schemas._2004._07.uploaddocumentresponse.UploadDocumentResponse sendBillAsync(
        @WebParam(name = "fileName", targetNamespace = "http://wcf.dian.colombia")
        java.lang.String fileName,
        @WebParam(name = "contentFile", targetNamespace = "http://wcf.dian.colombia")
        byte[] contentFile
    );

    @WebMethod(operationName = "SendBillSync", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendBillSync")
    @Action(input = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendBillSync", output = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendBillSyncResponse")
    @RequestWrapper(localName = "SendBillSync", targetNamespace = "http://wcf.dian.colombia", className = "colombia.dian.wcf.SendBillSync")
    @ResponseWrapper(localName = "SendBillSyncResponse", targetNamespace = "http://wcf.dian.colombia", className = "colombia.dian.wcf.SendBillSyncResponse")
    @WebResult(name = "SendBillSyncResult", targetNamespace = "http://wcf.dian.colombia")
    public org.datacontract.schemas._2004._07.dianresponse.DianResponse sendBillSync(
        @WebParam(name = "fileName", targetNamespace = "http://wcf.dian.colombia")
        java.lang.String fileName,
        @WebParam(name = "contentFile", targetNamespace = "http://wcf.dian.colombia")
        byte[] contentFile
    );

    @WebMethod(operationName = "SendBillAttachmentAsync", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendBillAttachmentAsync")
    @Action(input = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendBillAttachmentAsync", output = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendBillAttachmentAsyncResponse")
    @RequestWrapper(localName = "SendBillAttachmentAsync", targetNamespace = "http://wcf.dian.colombia", className = "colombia.dian.wcf.SendBillAttachmentAsync")
    @ResponseWrapper(localName = "SendBillAttachmentAsyncResponse", targetNamespace = "http://wcf.dian.colombia", className = "colombia.dian.wcf.SendBillAttachmentAsyncResponse")
    @WebResult(name = "SendBillAttachmentAsyncResult", targetNamespace = "http://wcf.dian.colombia")
    public org.datacontract.schemas._2004._07.uploaddocumentresponse.UploadDocumentResponse sendBillAttachmentAsync(
        @WebParam(name = "fileName", targetNamespace = "http://wcf.dian.colombia")
        java.lang.String fileName,
        @WebParam(name = "contentFile", targetNamespace = "http://wcf.dian.colombia")
        byte[] contentFile
    );

    @WebMethod(operationName = "GetStatusZip", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetStatusZip")
    @Action(input = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetStatusZip", output = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetStatusZipResponse")
    @RequestWrapper(localName = "GetStatusZip", targetNamespace = "http://wcf.dian.colombia", className = "colombia.dian.wcf.GetStatusZip")
    @ResponseWrapper(localName = "GetStatusZipResponse", targetNamespace = "http://wcf.dian.colombia", className = "colombia.dian.wcf.GetStatusZipResponse")
    @WebResult(name = "GetStatusZipResult", targetNamespace = "http://wcf.dian.colombia")
    public org.datacontract.schemas._2004._07.dianresponse.ArrayOfDianResponse getStatusZip(
        @WebParam(name = "trackId", targetNamespace = "http://wcf.dian.colombia")
        java.lang.String trackId
    );

    @WebMethod(operationName = "SendTestSetAsync", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendTestSetAsync")
    @Action(input = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendTestSetAsync", output = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendTestSetAsyncResponse")
    @RequestWrapper(localName = "SendTestSetAsync", targetNamespace = "http://wcf.dian.colombia", className = "colombia.dian.wcf.SendTestSetAsync")
    @ResponseWrapper(localName = "SendTestSetAsyncResponse", targetNamespace = "http://wcf.dian.colombia", className = "colombia.dian.wcf.SendTestSetAsyncResponse")
    @WebResult(name = "SendTestSetAsyncResult", targetNamespace = "http://wcf.dian.colombia")
    public org.datacontract.schemas._2004._07.uploaddocumentresponse.UploadDocumentResponse sendTestSetAsync(
        @WebParam(name = "fileName", targetNamespace = "http://wcf.dian.colombia")
        java.lang.String fileName,
        @WebParam(name = "contentFile", targetNamespace = "http://wcf.dian.colombia")
        byte[] contentFile,
        @WebParam(name = "testSetId", targetNamespace = "http://wcf.dian.colombia")
        java.lang.String testSetId
    );

    @WebMethod(operationName = "GetXmlByDocumentKey", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetXmlByDocumentKey")
    @Action(input = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetXmlByDocumentKey", output = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetXmlByDocumentKeyResponse")
    @RequestWrapper(localName = "GetXmlByDocumentKey", targetNamespace = "http://wcf.dian.colombia", className = "colombia.dian.wcf.GetXmlByDocumentKey")
    @ResponseWrapper(localName = "GetXmlByDocumentKeyResponse", targetNamespace = "http://wcf.dian.colombia", className = "colombia.dian.wcf.GetXmlByDocumentKeyResponse")
    @WebResult(name = "GetXmlByDocumentKeyResult", targetNamespace = "http://wcf.dian.colombia")
    public org.datacontract.schemas._2004._07.eventresponse.EventResponse getXmlByDocumentKey(
        @WebParam(name = "trackId", targetNamespace = "http://wcf.dian.colombia")
        java.lang.String trackId
    );

    @WebMethod(operationName = "GetExchangeEmails", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetExchangeEmails")
    @Action(input = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetExchangeEmails", output = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetExchangeEmailsResponse")
    @RequestWrapper(localName = "GetExchangeEmails", targetNamespace = "http://wcf.dian.colombia", className = "colombia.dian.wcf.GetExchangeEmails")
    @ResponseWrapper(localName = "GetExchangeEmailsResponse", targetNamespace = "http://wcf.dian.colombia", className = "colombia.dian.wcf.GetExchangeEmailsResponse")
    @WebResult(name = "GetExchangeEmailsResult", targetNamespace = "http://wcf.dian.colombia")
    public org.datacontract.schemas._2004._07.exchangeemailresponse.ExchangeEmailResponse getExchangeEmails();

    @WebMethod(operationName = "GetStatus", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetStatus")
    @Action(input = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetStatus", output = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetStatusResponse")
    @RequestWrapper(localName = "GetStatus", targetNamespace = "http://wcf.dian.colombia", className = "colombia.dian.wcf.GetStatus")
    @ResponseWrapper(localName = "GetStatusResponse", targetNamespace = "http://wcf.dian.colombia", className = "colombia.dian.wcf.GetStatusResponse")
    @WebResult(name = "GetStatusResult", targetNamespace = "http://wcf.dian.colombia")
    public org.datacontract.schemas._2004._07.dianresponse.DianResponse getStatus(
        @WebParam(name = "trackId", targetNamespace = "http://wcf.dian.colombia")
        java.lang.String trackId
    );
}
