package colombia.dian.wcf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2020-02-06T23:56:32.722+07:00
 * Generated source version: 3.3.1
 *
 */
@WebServiceClient(name = "WcfDianCustomerServices",
                  wsdlLocation = "https://vpfe-hab.dian.gov.co/WcfDianCustomerServices.svc?wsdl",
                  targetNamespace = "http://wcf.dian.colombia")
public class WcfDianCustomerServices extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://wcf.dian.colombia", "WcfDianCustomerServices");
    public final static QName WSHttpBindingIWcfDianCustomerServices = new QName("http://wcf.dian.colombia", "WSHttpBinding_IWcfDianCustomerServices");
    static {
        URL url = null;
        try {
            url = new URL("https://vpfe-hab.dian.gov.co/WcfDianCustomerServices.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WcfDianCustomerServices.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://vpfe-hab.dian.gov.co/WcfDianCustomerServices.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WcfDianCustomerServices(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WcfDianCustomerServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WcfDianCustomerServices() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WcfDianCustomerServices(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WcfDianCustomerServices(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WcfDianCustomerServices(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IWcfDianCustomerServices
     */
    @WebEndpoint(name = "WSHttpBinding_IWcfDianCustomerServices")
    public IWcfDianCustomerServices getWSHttpBindingIWcfDianCustomerServices() {
        return super.getPort(WSHttpBindingIWcfDianCustomerServices, IWcfDianCustomerServices.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWcfDianCustomerServices
     */
    @WebEndpoint(name = "WSHttpBinding_IWcfDianCustomerServices")
    public IWcfDianCustomerServices getWSHttpBindingIWcfDianCustomerServices(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingIWcfDianCustomerServices, IWcfDianCustomerServices.class, features);
    }

}
